// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_challenge_bravo.Model.Util;

namespace api_challenge_bravo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220319131139_CurrenciesCreate")]
    partial class CurrenciesCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api_challenge_bravo.Model.Currency", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("AutoUpdateExchangeRate")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("ExchangeRateInUSD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("LastTimeUpdatedExchangeRate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Symbol");

                    b.ToTable("Currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
