FROM node:12
WORKDIR /hurb_app
COPY *.json ./
RUN npm install
COPY src ./src
RUN npm run build

FROM node:12-alpine
WORKDIR /hurb_app
COPY --from=0 /hurb_app/dist .
COPY --from=0 /hurb_app/node_modules ./node_modules

# Add Dockerize to wait for dependencies
RUN apk add --no-cache openssl

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

CMD ["node", "index.js"]