# esses valores são locais, precisam das bibliotecas instaladas pelo pip no projeto.
# Pre-Commit carregado xD

default_language_version:
    python: python3.12

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
      - id: check-docstring-first
      - id: detect-private-key
      - id: name-tests-test
        args: [--django]

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [python, pyi]

    -   id: flake8
        args:
        - "--max-line-length=88"
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

    -   id: isort
        args:
        - "--profile"
        - "black"
        - "--filter-files"
        - "--force-grid-wrap=2"
        - "--multi-line=3"
        name: isort
        entry: isort
        require_serial: true
        language: python
