
FROM alpine:3.16

RUN apk add --update php-8.1

RUN touch crontab.tmp \
    && echo '* * * * * cd /var/www && php artisan schedule:run >> /dev/stdout 2>&1' > crontab.tmp \
    && crontab crontab.tmp \
    && rm -rf crontab.tmp

CMD ["/usr/sbin/crond", "-f", "-d", "0"]