FROM ubuntu:latest

COPY init_currencys_in_db.py init_currencys_in_db.py
# Add the script to the Docker Image
#ADD init_currencys_in_db.py /root/init_currencys_in_db.py

# Give execution rights on the cron scripts
RUN chmod 0644 init_currencys_in_db.py

#Install Cron
RUN apt-get update
RUN apt-get -y install cron

# Add the cron job
RUN crontab -l | { cat; echo "*/1 * * * * python /home/$USER/init_currencys_in_db.py"; } | crontab -

# # Run the command on container startup
# CMD cron

# 0 0 * * *
RUN echo "CRONJOB FINALIZADO!"
