// <auto-generated />
using System;
using ConversaoMonetaria.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConversaoMonetaria.Data.Migrations
{
    [DbContext(typeof(ConversaoMonetariaContext))]
    [Migration("20220707124226_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("ConversaoMonetaria.Dominio.Entidades.Moedas.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cotacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Moeda", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "BRL",
                            Cotacao = 5.4125m,
                            DataAtualizacao = new DateTime(2022, 7, 7, 9, 42, 26, 750, DateTimeKind.Local).AddTicks(2618),
                            DataCadastro = new DateTime(2022, 7, 7, 9, 42, 26, 750, DateTimeKind.Local).AddTicks(2626),
                            Nome = "Real Brasileiro",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "USD",
                            Cotacao = 1m,
                            DataAtualizacao = new DateTime(2022, 7, 7, 9, 42, 26, 750, DateTimeKind.Local).AddTicks(2631),
                            DataCadastro = new DateTime(2022, 7, 7, 9, 42, 26, 750, DateTimeKind.Local).AddTicks(2631),
                            Nome = "Dólar Americano",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
