// <auto-generated />
using System;
using ConversaoMonetaria.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConversaoMonetaria.Data.Migrations
{
    [DbContext(typeof(ConversaoMonetariaContext))]
    partial class ConversaoMonetariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("ConversaoMonetaria.Dominio.Entidades.Moedas.Moeda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cotacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Moeda", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Codigo = "BRL",
                            Cotacao = 1m,
                            DataCadastro = new DateTime(2022, 7, 8, 17, 53, 50, 723, DateTimeKind.Local).AddTicks(3603),
                            Nome = "Real Brasileiro",
                            Status = 0
                        },
                        new
                        {
                            Id = 2L,
                            Codigo = "USD",
                            Cotacao = 5.3407m,
                            DataCadastro = new DateTime(2022, 7, 8, 17, 53, 50, 723, DateTimeKind.Local).AddTicks(3615),
                            Nome = "Dólar Americano",
                            Status = 0
                        },
                        new
                        {
                            Id = 3L,
                            Codigo = "CAD",
                            Cotacao = 4.1108m,
                            DataCadastro = new DateTime(2022, 7, 8, 17, 53, 50, 723, DateTimeKind.Local).AddTicks(3617),
                            Nome = "Dólar Canadense",
                            Status = 0
                        },
                        new
                        {
                            Id = 4L,
                            Codigo = "GBP",
                            Cotacao = 6.4083m,
                            DataCadastro = new DateTime(2022, 7, 8, 17, 53, 50, 723, DateTimeKind.Local).AddTicks(3618),
                            Nome = "Libra Esterlina",
                            Status = 0
                        },
                        new
                        {
                            Id = 5L,
                            Codigo = "ARS",
                            Cotacao = 0.0422m,
                            DataCadastro = new DateTime(2022, 7, 8, 17, 53, 50, 723, DateTimeKind.Local).AddTicks(3620),
                            Nome = "Peso Argentino",
                            Status = 0
                        },
                        new
                        {
                            Id = 6L,
                            Codigo = "BTC",
                            Cotacao = 115.668m,
                            DataCadastro = new DateTime(2022, 7, 8, 17, 53, 50, 723, DateTimeKind.Local).AddTicks(3622),
                            Nome = "Bitcoin",
                            Status = 0
                        },
                        new
                        {
                            Id = 7L,
                            Codigo = "EUR",
                            Cotacao = 5.4235m,
                            DataCadastro = new DateTime(2022, 7, 8, 17, 53, 50, 723, DateTimeKind.Local).AddTicks(3624),
                            Nome = "Euro",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
