# Generated by Django 2.2.1 on 2019-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol')),
                ('is_base', models.BooleanField(db_index=True, verbose_name='Base Currency')),
                ('value', models.DecimalField(decimal_places=12, max_digits=25, verbose_name='Value comparing to Base')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
