FROM python:3.9.7

# Fix psycopg2 issue
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && apt-get install -y libpq-dev \
    && apt-get install -y build-essential \
    && apt-get install -y python-dev \
    && pip install --upgrade pip \
    && pip install psycopg2 \
    && pip install psycopg2-binary

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . ./

CMD [ "python", "./script.py"]