import {AfterViewInit, Component, OnInit, ViewChild, ViewEncapsulation} from "@angular/core";
import {DataService} from "../../service/data.service";
import {InputNumber} from "primeng/inputnumber";
import {Currency} from "../../model/currency";
import {formatNumber} from "@angular/common";

@Component({
  encapsulation: ViewEncapsulation.None,
  selector: 'app-currency-converter',
  styleUrls: ['./currency-converter.component.scss'],
  templateUrl: './currency-converter.component.html',
})
export class CurrencyConverterComponent implements OnInit, AfterViewInit {

  @ViewChild('eamount')
  public amountInput!: InputNumber; // Direct access to DOM element using #, will be used to add tel type to component for mobile devices

  amount = 10; // Currency amount to be converted
  from?: Currency; // From currency to be converted
  to?: Currency; // To currency to be converted
  resultLabel: string = "---" // Conversion result label

  /**
   * Class constructor
   * @param {DataService} dataService - Service that obtain data from bravo server
   * */
  constructor(private readonly dataService: DataService) {
  }

  /**
   * Class initialization
   */
  ngOnInit(): void {

    // Clear caches at component start up
    this.dataService.clearCurrenciesCache();
    this.dataService.clearConversionCache();

    // Load component with default values
    this.dataService.getCurrencies().subscribe(currencies => {
      this.from = currencies.find(curr => curr.code == 'BRL');
      this.to = currencies.find(curr => curr.code == 'USD');
      this.onChange({});
    });
  }

  /**
   * Runs when then view is initialized
   */
  public ngAfterViewInit(): void {
    // Adds type tel to input element to show numeric keyboard on mobile devices
    (this.amountInput.input.nativeElement as HTMLElement).setAttribute("type", "tel");
  }

  /**
   * Executed when from, to or amount user inputs changes
   * @param {any} event - Event generated by user input
   */
  onChange(event: any): void {
    let amount = 'value' in event ? parseFloat(event.value) : this.amount;
    if (this.to === null || this.from === null) {
      return;
    }

    // @ts-ignore
    this.dataService.convert(amount, this.from, this.to).subscribe(response => {
      this.resultLabel = `${formatNumber(response.quote, "en-US", "1.2-5")} ${this.to?.code}`;
    });
  }

}
