# Generated by Django 3.2.4 on 2021-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('nameDescription', models.CharField(max_length=255)),
                ('baseUsdValue', models.DecimalField(decimal_places=4, max_digits=10)),
                ('typeCurrency', models.CharField(choices=[(1, 'REAL'), (2, 'VIRTUAL')], default=1, max_length=2)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('quotationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
