# Generated by Django 3.2.4 on 2021-06-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='symbol',
            new_name='symbolAlias',
        ),
    ]
