# Generated by Django 3.2.4 on 2021-06-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_symbol_currency_symbolalias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='creationDate',
            new_name='lastUpdateDate',
        ),
    ]
