# Generated by Django 3.2.4 on 2021-06-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_rename_creationdate_currency_lastupdatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbolAlias',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
