# Generated by Django 3.1.2 on 2020-10-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
