# flake8: noqa
"""init

Revision ID: 035876418c9d
Revises: 
Create Date: 2021-10-30 19:44:51.562518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035876418c9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(precision=10, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=False)
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
