"""fix currency_type default value

Revision ID: 0b77b33f460f
Revises: fdabd90622dc
Create Date: 2022-09-03 04:52:11.343808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b77b33f460f'
down_revision = 'fdabd90622dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fantasy_coins', sa.Column('currency_type', sa.String(), server_default='fantasy', nullable=False))
    op.create_index(op.f('ix_fantasy_coins_currency_type'), 'fantasy_coins', ['currency_type'], unique=False)
    op.add_column('oficial_coins', sa.Column('currency_type', sa.String(), server_default='oficial', nullable=False))
    op.create_index(op.f('ix_oficial_coins_currency_type'), 'oficial_coins', ['currency_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oficial_coins_currency_type'), table_name='oficial_coins')
    op.drop_column('oficial_coins', 'currency_type')
    op.drop_index(op.f('ix_fantasy_coins_currency_type'), table_name='fantasy_coins')
    op.drop_column('fantasy_coins', 'currency_type')
    # ### end Alembic commands ###
