"""create currencies tables

Revision ID: 5b289bd836e1
Revises: 
Create Date: 2022-12-06 09:42:14.794862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b289bd836e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "created_currencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("currency_code", sa.String(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("backed_by", sa.String(), server_default="USD", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # insert column currency_type
        sa.Column(
            "currency_type", sa.String(), server_default="created", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_created_currencies_currency_code"),
        "created_currencies",
        ["currency_code"],
        unique=True,
    )

    op.create_table(
        "coinbase_currencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("currency_code", sa.String(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("backed_by", sa.String(), server_default="USD", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "currency_type", sa.String(), server_default="coinbase", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coinbase_currencies_currency_code"),
        "coinbase_currencies",
        ["currency_code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_coinbase_currencies_currency_code"),
        table_name="coinbase_currencies",
    )
    op.drop_table("coinbase_currencies")
    op.drop_index(
        op.f("ix_created_currencies_currency_code"),
        table_name="created_currencies",
    )
    op.drop_table("created_currencies")
