# flake8: noqa
"""empty message

Revision ID: 63279c6e9401
Revises: 035876418c9d
Create Date: 2021-11-01 18:10:41.737787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63279c6e9401'
down_revision = '035876418c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currency_code', table_name='currency')
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.create_index('ix_currency_code', 'currency', ['code'], unique=False)
    # ### end Alembic commands ###
