"""create favorite_coins table

Revision ID: 8f2e152bb468
Revises: 0b77b33f460f
Create Date: 2022-09-04 00:46:38.417659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2e152bb468'
down_revision = '0b77b33f460f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('currency_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_coins_currency_code'), 'favorite_coins', ['currency_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_coins_currency_code'), table_name='favorite_coins')
    op.drop_table('favorite_coins')
    # ### end Alembic commands ###
