"""create oficial_coins and fantasy_coins table

Revision ID: fdabd90622dc
Revises: 
Create Date: 2022-09-03 00:04:30.032150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdabd90622dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('backed_by', sa.String(), server_default='USD', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_coins_currency_code'), 'fantasy_coins', ['currency_code'], unique=True)
    op.create_table('oficial_coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('backed_by', sa.String(), server_default='USD', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oficial_coins_currency_code'), 'oficial_coins', ['currency_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oficial_coins_currency_code'), table_name='oficial_coins')
    op.drop_table('oficial_coins')
    op.drop_index(op.f('ix_fantasy_coins_currency_code'), table_name='fantasy_coins')
    op.drop_table('fantasy_coins')
    # ### end Alembic commands ###
