// Code generated by mockery v2.9.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ConversionController is an autogenerated mock type for the ConversionController type
type ConversionController struct {
	mock.Mock
}

// Convert provides a mock function with given fields: c
func (_m *ConversionController) Convert(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewConversionController interface {
	mock.TestingT
	Cleanup(func())
}

// NewConversionController creates a new instance of ConversionController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConversionController(t mockConstructorTestingTNewConversionController) *ConversionController {
	mock := &ConversionController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
