// Code generated by mockery v2.9.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ConversionHandler is an autogenerated mock type for the ConversionHandler type
type ConversionHandler struct {
	mock.Mock
}

// Convert provides a mock function with given fields: c
func (_m *ConversionHandler) Convert(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewConversionHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewConversionHandler creates a new instance of ConversionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConversionHandler(t mockConstructorTestingTNewConversionHandler) *ConversionHandler {
	mock := &ConversionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
