// Code generated by mockery v2.9.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyHandler is an autogenerated mock type for the CurrencyHandler type
type CurrencyHandler struct {
	mock.Mock
}

// CreateCurrency provides a mock function with given fields: c
func (_m *CurrencyHandler) CreateCurrency(c *gin.Context) {
	_m.Called(c)
}

// DeleteCurrency provides a mock function with given fields: c
func (_m *CurrencyHandler) DeleteCurrency(c *gin.Context) {
	_m.Called(c)
}

// GetAllCurrencies provides a mock function with given fields: c
func (_m *CurrencyHandler) GetAllCurrencies(c *gin.Context) {
	_m.Called(c)
}

// GetCurrencyByID provides a mock function with given fields: c
func (_m *CurrencyHandler) GetCurrencyByID(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewCurrencyHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrencyHandler creates a new instance of CurrencyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrencyHandler(t mockConstructorTestingTNewCurrencyHandler) *CurrencyHandler {
	mock := &CurrencyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
