// Code generated by mockery v2.9.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CurrencySeed is an autogenerated mock type for the CurrencySeed type
type CurrencySeed struct {
	mock.Mock
}

// SeedInitialCurrency provides a mock function with given fields:
func (_m *CurrencySeed) SeedInitialCurrency() {
	_m.Called()
}

type mockConstructorTestingTNewCurrencySeed interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrencySeed creates a new instance of CurrencySeed. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrencySeed(t mockConstructorTestingTNewCurrencySeed) *CurrencySeed {
	mock := &CurrencySeed{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
