// Code generated by mockery v2.9.6. DO NOT EDIT.

package mocks

import (
	entities "github.com/felipepnascimento/challenge-bravo-flp/entities"
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyHandler is an autogenerated mock type for the CurrencyHandler type
type CurrencyHandler struct {
	mock.Mock
}

// CreateCurrency provides a mock function with given fields: ctx
func (_m *CurrencyHandler) CreateCurrency(ctx *gin.Context) *entities.AppResult {
	ret := _m.Called(ctx)

	var r0 *entities.AppResult
	if rf, ok := ret.Get(0).(func(*gin.Context) *entities.AppResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AppResult)
		}
	}

	return r0
}

// DeleteCurrency provides a mock function with given fields: ctx
func (_m *CurrencyHandler) DeleteCurrency(ctx *gin.Context) *entities.AppResult {
	ret := _m.Called(ctx)

	var r0 *entities.AppResult
	if rf, ok := ret.Get(0).(func(*gin.Context) *entities.AppResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AppResult)
		}
	}

	return r0
}

// GetAllCurrencies provides a mock function with given fields: ctx
func (_m *CurrencyHandler) GetAllCurrencies(ctx *gin.Context) *entities.AppResult {
	ret := _m.Called(ctx)

	var r0 *entities.AppResult
	if rf, ok := ret.Get(0).(func(*gin.Context) *entities.AppResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AppResult)
		}
	}

	return r0
}

// GetCurrencyByID provides a mock function with given fields: ctx
func (_m *CurrencyHandler) GetCurrencyByID(ctx *gin.Context) *entities.AppResult {
	ret := _m.Called(ctx)

	var r0 *entities.AppResult
	if rf, ok := ret.Get(0).(func(*gin.Context) *entities.AppResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AppResult)
		}
	}

	return r0
}

type mockConstructorTestingTNewCurrencyHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrencyHandler creates a new instance of CurrencyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrencyHandler(t mockConstructorTestingTNewCurrencyHandler) *CurrencyHandler {
	mock := &CurrencyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
