# Generated by Django 4.1.2 on 2022-10-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fictionalcurrency",
            options={
                "verbose_name": "Moeda Fictícia",
                "verbose_name_plural": "Moedas Fictícias",
            },
        ),
        migrations.AlterField(
            model_name="fictionalcurrency",
            name="currency_short_name",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Nome da Moeda Abreviado"
            ),
        ),
    ]
