"""empty message

Revision ID: 8933e1ba5f5f
Revises: 
Create Date: 2022-06-28 12:08:32.999759

"""
import sqlalchemy as sa
from alembic import op

from app.configs import populate_currencies_table

# revision identifiers, used by Alembic.
revision = "8933e1ba5f5f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tb_curencies = op.create_table(
        "currencies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("backing_currency", sa.Boolean(), nullable=True),
        sa.Column("is_crypto", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "cotations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("from_currency_id", sa.String(), nullable=True),
        sa.Column("to_currency_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_currency_id"],
            ["currencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    # ### end Alembic commands ###

    populate_currencies_table(tb_curencies)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cotations")
    op.drop_table("currencies")
    # ### end Alembic commands ###
