// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "conversion-api/models"

	mock "github.com/stretchr/testify/mock"
)

// Gateway is an autogenerated mock type for the Gateway type
type Gateway struct {
	mock.Mock
}

// GetCurrencyByName provides a mock function with given fields: _a0
func (_m *Gateway) GetCurrencyByName(_a0 string) (models.Currency, error) {
	ret := _m.Called(_a0)

	var r0 models.Currency
	if rf, ok := ret.Get(0).(func(string) models.Currency); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Currency)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
