# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  desafiobravobackend:
    image: desafiobravobackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    environment:
      - Database:Name=Data Source = ./app.db
