# Generated by Django 4.1.4 on 2022-12-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('rate', models.FloatField()),
                ('type', models.CharField(choices=[('fiat', 'FIAT'), ('crypto', 'Crypto'), ('fictional', 'Fictional')], default='fiat', max_length=50)),
                ('backed_to', models.CharField(default='USD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
