# Generated by Django 4.0.4 on 2022-06-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Value (R$)'),
        ),
    ]
