# Generated by Django 3.2.3 on 2021-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('code', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('value', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
