# Generated by Django 3.2.4 on 2021-06-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=100, unique=True)),
                ('coin_initials', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('country_initials', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'coin',
            },
        ),
    ]
