# Generated by Django 3.2.4 on 2021-06-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmodel',
            name='bslt',
            field=models.CharField(default='USD', max_length=100, unique=False),
            preserve_default=False,
        ),
    ]
