# Generated by Django 3.2.4 on 2021-06-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_coinmodel_bslt'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmodel',
            name='amount_coint',
            field=models.FloatField(default=1),
        ),
    ]
