# Generated by Django 3.2.4 on 2021-06-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_coinmodel_amount_coint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinmodel',
            old_name='amount_coint',
            new_name='amount_coint_bslt',
        ),
    ]
