# Flask settings
FLASK_SERVER_NAME = 'localhost:5000'
FLASK_DEBUG = True # Use false for production

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False


# ENV VAR!
MOCK_CURRENCY_PROVIDER = False
CURRENCY_LAYER_API_KEY = 'b2e6a2239dc35b519f74ea6c761fc6f7'
