# Generated by Django 3.2.6 on 2021-08-12 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('codecoin', models.CharField(max_length=3, verbose_name='Code Coin')),
                ('namecoin', models.CharField(max_length=50, verbose_name='Name Coin')),
            ],
            options={
                'verbose_name': 'My Coin',
                'verbose_name_plural': 'My Coins',
                'ordering': ('namecoin',),
            },
        ),
        migrations.AddConstraint(
            model_name='mycoin',
            constraint=models.UniqueConstraint(fields=('codecoin',), name='unique_mycoin_codecoin'),
        ),
    ]
