# Generated by Django 3.2.6 on 2021-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mycoin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycoin',
            name='codecoin',
            field=models.CharField(max_length=4, verbose_name='Code Coin'),
        ),
        migrations.AlterField(
            model_name='mycoin',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price USD Coin'),
        ),
    ]
